WHGSchedulerSite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WHGScheduler.Repository;
using WHGSchedulerSite.ViewModels;

namespace WHGSchedulerSite.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View( new SponsorsViewModel() {
                sponsorList = Sponsor.GetList(true)
            });
        }
    }
}

WHGSchedulerSite/Controllers/MeetingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WHGScheduler.Repository;
using WHGScheduler.Repository.Models;
using WHGSchedulerSite.ViewModels;

namespace WHGSchedulerSite.Controllers
{
    public class MeetingsController : Controller
    {
        public ActionResult Index(int sponsor)
        {
            Meeting.GetListByDay(sponsor);

            return View( new SponsorMeetingsViewModel() {
                sponsor = Sponsor.GetByID(sponsor),
                meetings = Meeting.GetListByDay(sponsor)
            });
        }

        [HttpPost]
        public JsonResult SaveRegistrant(RegistrantModel registrant)
        {
            bool success = true;

            Registrant.Save(registrant);

            return Json(new { Success = success });
        }
    }
}

WHGSchedulerSite/Views/Home/Index.cshtml
@model WHGSchedulerSite.ViewModels.SponsorsViewModel

<div class="row">
    <div class="col-md-12">
        <h1 class="title text-primary">
            <b>Maximize Your Time at Conference</b><br /><br /><i>Visit with WHG departments or Platinum and Gold supplier partners with a pre-booked appointment.</i>
        </h1>
        <p class="instructions text-muted">
            Why wait on line at the trade show to speak with platinum or gold supplier or a Global Village team member when you can schedule a personal appointment? To do so:
        </p>
        <ol class="instructions text-muted">
            <li>Visit either the Supplier Partner or Global Village section below.</li>
            <li>Click the arrow to reveal your options.</li>
            <li>Click the Meet button for your selected supplier or department to view the available schedule.</li>
            <li>Select a time that works for you to secure a guaranteed meeting.</li>
        </ol>
        <p class="instructions text-muted">After you select a meeting time and fill out the required information, you will receive a confirmation email with all of the details. It’s that easy!</p>
        <p class="instructions text-muted">If you have any questions, please contact Bert Guy, bert@onyxmeetings.com.</p>
    </div>
</div>

<div class="row body-nav">
    <div class="col-md-12">
        <button id="btn-supplier-partners" class="btn btn-block btn-lg btn-primary large-nav" type="button" data-toggle="collapse" data-target="#supplier-partners">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>Platinum and Gold Supplier Partners
        </button>
    </div>
</div>

<div class="row collapse" id="supplier-partners">
    @foreach (var sponsor in Model.sponsorList.Where(s => s.type == "Supplier Partners"))
    {
        <div class="col-md-4">
            <div class="thumbnail">
                <img src="~/assets/img/logos/@sponsor.logoImage" alt="...">
                <div class="caption">
                    <p style="text-align: center">
                        <a href="@Url.Action("Index", "Meetings", new {sponsor = @sponsor.id})" class="btn btn-primary" role="button">Meet</a>
                    </p>
                </div>
            </div>
        </div>
    }
</div>

<div class="row body-nav">
    <div class="col-md-12">
        <button id="btn-global-village" class="btn btn-block btn-lg btn-info large-nav" type="button" data-toggle="collapse" data-target="#global-village">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>WHG Global Village
        </button>
    </div>
</div>

<div class="row collapse" id="global-village">
    @foreach (var sponsor in Model.sponsorList.Where(s => s.type == "WHG Global Village"))
    {
        <div class="col-md-4">
            <div class="thumbnail">
                <img src="~/assets/img/logos/@sponsor.logoImage" alt="...">
                <div class="caption">
                    <p style="text-align: center">
                        <a href="@Url.Action("Index", "Meetings", new {sponsor = @sponsor.id})" class="btn btn-primary" role="button">Meet</a>
                    </p>
                </div>
            </div>
        </div>
    }
</div>